### ISSUE TITLE
npm run build:development 

### ISSUE THREAD

**Issue by pretech86** [martinsuba/code-injector-extension#10]
it give me the following error 

> code-injector@1.0.0 build:production /root/tools/web applications/code-injector-extension/extension
> npm run clean && node ./taskfile.js --mode=production

> code-injector@1.0.0 clean /root/tools/web applications/code-injector-extension/extension
> del-cli build

> code-injector-ui@0.1.0 build /root/tools/web applications/code-injector-extension/ui
> react-scripts build

sh: 1: react-scripts: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! code-injector-ui@0.1.0 build: `react-scripts build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the code-injector-ui@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-01T09_04_45_004Z-debug.log
Error: Command failed: /bin/sh -c cd ../ui && npm run build
sh: 1: react-scripts: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! code-injector-ui@0.1.0 build: `react-scripts build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the code-injector-ui@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-01T09_04_45_004Z-debug.log

> code-injector-ui@0.1.0 build /root/tools/web applications/code-injector-extension/ui
> react-scripts build

    at makeError (/root/tools/web applications/code-injector-extension/extension/node_modules/execa/index.js:174:9)
    at /root/tools/web applications/code-injector-extension/extension/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /root/tools/web applications/code-injector-extension/extension/taskfile.js:7:5 {
  code: 1,
  stdout: '\n' +
    '> code-injector-ui@0.1.0 build /root/tools/web applications/code-injector-extension/ui\n' +
    '> react-scripts build\n' +
    '\n',
  stderr: 'sh: 1: react-scripts: not found\n' +
    'npm ERR! code ELIFECYCLE\n' +
    'npm ERR! syscall spawn\n' +
    'npm ERR! file sh\n' +
    'npm ERR! errno ENOENT\n' +
    'npm ERR! code-injector-ui@0.1.0 build: `react-scripts build`\n' +
    'npm ERR! spawn ENOENT\n' +
    'npm ERR! \n' +
    'npm ERR! Failed at the code-injector-ui@0.1.0 build script.\n' +
    'npm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n' +
    '\n' +
    'npm ERR! A complete log of this run can be found in:\n' +
    'npm ERR!     /root/.npm/_logs/2020-02-01T09_04_45_004Z-debug.log\n',
  failed: true,
  signal: null,
  cmd: '/bin/sh -c cd ../ui && npm run build',
  timedOut: false,
  killed: false

**Comment by martinsuba** [comment]
@pretech86 Seems like you missing `react-scripts` dependency in the `ui` folder. Have you run `npm i` in the ui folder?

**Comment by pretech86** [comment]
it give me the following 

npm run build:production

> code-injector@1.0.0 build:production /root/tools/web applications/code-injector-extension/extension
> npm run clean && node ./taskfile.js --mode=production


> code-injector@1.0.0 clean /root/tools/web applications/code-injector-extension/extension
> del-cli build


> code-injector-ui@0.1.0 build /root/tools/web applications/code-injector-extension/ui
> react-scripts build

Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  56.7 KB  build/static/js/2.db4b71fd.chunk.js
  3.93 KB  build/static/js/main.3f1f30e2.chunk.js
  1.83 KB  build/static/css/main.11c71abb.chunk.css
  735 B    build/static/js/runtime-main.f3e47f32.js

The project was built assuming it is hosted at ./.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.

Find out more about deployment here:

  bit.ly/CRA-deploy

Time: 30564ms
Built at: 02/03/2020 5:08:03 AM
Entrypoint background = background.js
Entrypoint content-script = content-script.js
root@kali:~/tools/web applications/code-injector-extension/extension#

**Comment by martinsuba** [comment]
I belive your you can find the unpacked extension in the `extension/build` folder now.

**Comment by pretech86** [comment]
sorry i'm a beginner , what i should do with ths package ,, host it or what .. sorry to interrupt you

**Comment by martinsuba** [comment]
This is a chrome extension, so you should load it to google chrome:
https://webkul.com/blog/how-to-install-the-unpacked-extension-in-chrome/

**Comment by pretech86** [comment]
Thanks for kindly interest
