### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by pretech86** [martinsuba/code-injector-extension#9]
when i use npm run build 

npm run build
npm ERR! missing script: build

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-30T13_59_25_832Z-debug.log

**Comment by martinsuba** [comment]
@pretech86 Sorry I haven't updated the readme. It's `npm run build:development` or `npm run build:production`. I'm going to fix the readme file.

**Comment by pretech86** [comment]
It give me The same error
